#PRACTICA 10: ENSAMPLAJE DE GENOMAS

#instalamos el programa "hifiasm": 

```{bash} 
if [ ! -d ~/bin ]; then mkdir ~/bin; fi
cd ~/bin
git clone https://github.com/chhylp123/hifiasm
cd hifiasm
make ]
```

#hacemos que hifiasm este disponible en Path: 
```{bash}
export PATH=$PATH:~/bin/hifiasm
echo 'export PATH=$PATH:~/bin/hifiasm' >> ~/.bashrc
```
#EJERCICIO: 
#¿Cuántas secuencias contiene el archivo?
# R: en un primer momento lo que haremos será intentar leer el documento sin descomprimirlo.
```{bash}
zgrep -c "^>" ../../data/At4.10.fa.gz
```
# R: obtenemos un valor de 13812

#¿Qué longitudes mínima, media y máxima tienen las secuencias?
```{bash}
zcat ../../data/At4.10.fa.gz | awk '$0 ~ ">" {if (NR > 1) {print c; if 
(c<min || min=="") min=c; if (c>max) max=c; total+=c; count++} c=0; next} 
{c+=length($0)} END {print c; if (c<min || min=="") min=c; if (c>max) max=c; 
total+=c; count++; print "Min: " min; print "Max: " max; print "Total: " total; 
print "Media: " total/count}'
```
# R: usando el comando anterior en Bash obtenemos los siguientes resultados: 
# Min: 2942
# Max: 59075
# Total: 250599484
# Media: 18143.6

#¿Cuál es el número total de bases?
```{bash}
zcat ../../data/At4.10.fa.gz | grep -v "^>" | tr -d '\n' | wc -m
```
# R: 250599484
#Si se estimara que el genoma a ensamblar fuera de sólo 19 millones de bases, 
#¿cuál sería la cobertura esperada?
#usaremos el siguiente conjunto de comandos: 
# Contar secuencias
```{bash}
  zgrep -c "^>" ../../data/At4.10.fa.gz
```
# Calcular estadísticas de longitud y total de bases
```{bash}
zcat ../../data/At4.10.fa.gz | awk '
    /^>/ {
        if (seqlen) {
            sum += seqlen;
            if (seqlen > max) max = seqlen;
            if (seqlen < min) min = seqlen;
            count++;
        }
        seqlen = 0;
        next;
    }
    { seqlen += length($0) }
    END {
        sum += seqlen;
        if (seqlen > max) max = seqlen;
        if (seqlen < min) min = seqlen;
        count++;
        print "Num_Secuencias: " count;
        print "Total_Bases: " sum;
        print "Min: " min;
        print "Max: " max;
        print "Media: " sum/count;
    }'
```
#R: y obtenemos los siguientes resultados: 13812
# Num_Secuencias: 13812
# Total_Bases: 250599484
# Min:
# Max: 59075
# Media: 18143.6

#ENSAMBLAJE: 
#primero creamos unca carpeta donde lleavremos a capo el siguiente analisis:
# Con la ejecución condicional nos ahorramos algún mensaje de error:
```{bash}
if [ ! -d asm1 ]; then mkdir asm1; fi
```
#ahora llevamos a cabo el ensamblaje: 
#| cache: true #este comando es para no tener que ejecutar el ensamblaje cada 
#| #que compilamos el documento.
#| cache: true
```{bash}
export PATH="$PATH:$HOME/bin/hifiasm"
if [ ! -e asm1/At4.bp.p_ctg.gfa ]; then
hifiasm -o asm1/At4 -t 2 -f 0 ../../data/At4.10.fa.gz 2> asm1/hifiasm.log
fi
```
#EJERCICIO: 
#Consulta la ayuda de hifiasm (hifiasm -h) y contesta las preguntas siguientes:
#¿Los parámetros corresponden al ensamblaje de un genoma haploide o diploide?
# R: Usando el siguiente comando en Bash "hifiasm -h" obtenemos la respuesta: 
# en nuestro caso estamos tratando el ensamblaje como haploide.

#¿Qué nivel de eliminación de duplicaciones hemos aplicado? (El paso de eliminar 
#duplicaciones sirve para que las zonas de alta heterocigosidad no sean 
#ensambladas como contigs diferentes).
# R: el nivel de eliminacion está desactivado, esto lo sabemos por el parametro "-f 0" el cual controla la purga de contigs duplicatedos. 

#Si tuvieramos lecturas ultra-largas, ¿con qué opción o argumento añadiríamos 
#esa información?
# R: Usariamos la opcion "--ul <file>" que "file" hace referencia al archivo donde estan las lecturas ultra largas en formato FASTA o FASTQ. 

#EJERCICIO: 
#¿Dónde están las secuencias que componen el ensamblaje?
#R: Los debemos encontrar en los archivos del tipo .gfa, en nuestro caso el At4.bp.p_ctg.gfa que hemos generado. 
#En los archivos .gfa, ¿qué son las líneas que empiezan por ‘A’?
# R: hacen referencia a los caminos de las lecturas, es decir, los "Paths". 
#¿Qué información tiene los archivos .bed?
# R: tienen las coordenadas de los segmentos purgados, es decir, de los descartados y, por lo tanto, los duplicados por heterogeneidad o errores. 
#¿Cuál es la cobertura media estimada de las secuencias homocigotas?
# R: este punto se identifica como el pico de mayor cobertura
#¿Y la de las heterocigotas?
# R: en este caso el pico  corresponde a la mitad de la cobertura homocigotica. 

#CALIDAD DEL ENSAMBLAJE: 
# R: tras instalar el programa "Compleasm" y tras confirmar que "compleasm.py" esta dentro de "~/bin/compleasm_kit"
# descargamos la lista de genes para el ensamblaje: 
```{bash}
  if [ ! -e asm1_eval/summary.txt ]; then
python3 ~/bin/compleasm_kit/compleasm.py run \
-t 2 -l brassicales -a asm1/At4.fa -o asm1_eval
fi
```
# R: En este comando lo que hacemos es comprobar que los ensamblajes se han dado bien
# "-e asm1_eval/summary.txt" esta primera linea hace que si ya tenemos los resultados,no se vuelvan a ejecutar porque tarda mucho. 
# "python3 ~/bin/compleasm_kit/compleasm.py run" con este comando lo que hacemos es hacer que Python ejecute el script. El resto son caracteristicas que quiero que se  tengan en cuenta en el momento de la ejecucion. 
#RESULTADOS: 
# S:16.17%, 697
# D:0.14%, 6
# F:0.19%, 8
# I:0.00%, 0
# M:83.51%, 3600
# N:4311

## Download lineage: 23.69(s)
## Run miniprot: 1649.32(s)
## Analyze miniprot: 454.06(s)
## Total runtime: 2127.07(s)

#VISUALIZACION DEL GRAFO: 
# R: instalamos "Bandage" que es el unico programa de visualizacion de ensamblajes  como grafos de fragmentos, para ello usamos el siguiente comando en Bash: 

# 1. Entra en tu carpeta de programas
```{bash}
cd ~/bin

# 2. Descarga el ejecutable para Linux
wget https://github.com/rrwick/Bandage/releases/download/v0.8.1/Bandage_Linux_static_v0_8_1.zip

# 3. Descomprime el archivo
unzip Bandage_Linux_static_v0_8_1.zip

# 4. Dale permisos de ejecución
chmod +x Bandage

# 5. (Opcional) Pruébalo
./Bandage --help
```
